name: thuctapcoso
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

# The following line prevents the package from being accidentally published to
environment:
  sdk: ^3.6.1

# Package dependencies
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.1.1
  lottie: ^2.7.0
  connectivity_plus: ^4.0.0
  cloudinary_public: ^0.20.0
  image_picker: ^1.0.7
  path: ^1.8.3
  uuid: ^4.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  
  # Firebase Packages
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6
  firebase_analytics: ^11.4.6
  google_sign_in: ^6.1.0

  # icons
#  icons_ax: ^1.0.0
  cupertino_icons: ^1.0.8

  # state Management
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.4

  # product Specific
  readmore: ^2.2.0
#  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1 
  qr_flutter: ^4.1.0
#  carousel_slider: ^4.2.1

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Local assets
  assets:
    - assets/images/content/
    - assets/logos/
    - assets/icons/brands/
    - assets/images/banners/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/products/
    - assets/icons/payment_methods/
    

  # Local fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

 