// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAM-vV6nTadUN5UjG-twsX1f3jR54G2SM',
    appId: '1:1025994699992:web:60e42245987a54659353ad',
    messagingSenderId: '1025994699992',
    projectId: 'ecommerceapp-c10ae',
    authDomain: 'ecommerceapp-c10ae.firebaseapp.com',
    storageBucket: 'ecommerceapp-c10ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi8y0-z3GfsPFsJCi_ixNwDV6FhdRJLvU',
    appId: '1:1025994699992:android:261af857b9b754f39353ad',
    messagingSenderId: '1025994699992',
    projectId: 'ecommerceapp-c10ae',
    storageBucket: 'ecommerceapp-c10ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKgZPZiugBgF0iDncjm23wMSo302NDFtY',
    appId: '1:1025994699992:ios:3fb8ab9874559bc49353ad',
    messagingSenderId: '1025994699992',
    projectId: 'ecommerceapp-c10ae',
    storageBucket: 'ecommerceapp-c10ae.firebasestorage.app',
    androidClientId: '1025994699992-rmrdoidef23i5c7ljsh6ggibj62ni8k5.apps.googleusercontent.com',
    iosClientId: '1025994699992-i7b3ltkdba7vph5vskp9k44h3vmg09iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.thuctapcoso',
  );

}